name: rcsenv
channels: [conda-forge, defaults]
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - ipykernel
  - pip
  - pip:
      - tqdm
      - pyyaml
      - joblib
      - seaborn
      - scikit-rf
      - torch
      - torchvision
      - torchaudio
